### ISSUE TITLE
How to make use of this?

### ISSUE THREAD

**Issue by geofstro** [alessiomastrorillo/UHJdecoder#2]
It's very cool that you've made a UHJ Decoder in Max/MSP!

I'm looking to implement a UHJ Decoder in realtime; but I'm not at all familiar with Max/MSP.

Any chance of porting this to a C type language, … or even better for me, Swift for IOS/MacOS.

Will there be any documentation? For example how would one go about feeding a UHJ encoded Stereo file into this process and having it decoded to 4.0, 5.1, Binaural; etc?

Thanks for your time and effort. Nobody else seems to be doing anything with UHJ these days; but immersive/Multichannel/Spatial are all gaining in popularity.

**Comment by alessiomastrorillo** [comment]
Yes, this algorithm could work in other languages, C included. 

For documentation, you can refer to Gerzon's papers. Also, you could look at our speech to the NYCEMF, here's the proceeding:
https://nycemf.org/2023-paper-schedule/ (refer to the first paper)

And yes, one could decode UHJ into other formats. Four channels UHJ can decode back into a complete E-format, which is a complete spheric format, for further conversions.

With two channels (left/right) UHJ there is no Z component, so information about the elevation is lost, you only preserve horizontal components.

**Comment by geofstro** [comment]
Thanks I will take a look at your speech and read Gerzen's papers.
